[package]
name = "start"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
rand = "0.8.5"
regex = "1.9.1"
time = "0.3.23"
time-macros = "0.2.10"
unicode-segmentation = "1.10.1"
